In [1]:
import pandas as pd

In [2]:


df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
0,TXN507808,CUST102534,2023-01-01,51,Male,Chennai,Online,Flipkart,Clothing,Kurta,...,NaN,0,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly
1,TXN503830,CUST101256,2023-01-01,27,Female,Mumbai,Offline,NaN,Clothing,Shirt,...,NaN,0,NaN,0,No,UPI,5,Not Returned,0,Fortnightly
2,TXN501496,CUST100490,2023-01-01,57,Male,Hyderabad,Online,Flipkart,Clothing,Jacket,...,NaN,0,Standard,7,Yes,UPI,3,Not Returned,0,Rarely
3,TXN501538,CUST100500,2023-01-01,22,Female,Pune,Online,Myntra,Clothing,Kurta,...,NaN,0,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly
4,TXN504265,CUST101399,2023-01-01,30,Male,Visakhapatnam,Online,Myntra,Accessories,Cap,...,NaN,99,Express,2,No,Debit Card,4,Not Returned,0,Weekly

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction ID          10000 non-null  str
 1   Customer ID             10000 non-null  str
 2   Purchase Date           10000 non-null  str
 3   Age                     10000 non-null  int64
 4   Gender                  10000 non-null  str
 5   Location                10000 non-null  str
 6   Online/Offline          10000 non-null  str
 7   Online Store            7751 non-null   str
 8   Category                10000 non-null  str
 9   Item Purchased          10000 non-null  str
 10  Brand                   10000 non-null  str
 11  Color                   10000 non-null  str
 12  Size                    8965 non-null   str
 13  Quantity                10000 non-null  int64
 14  Purchase Amount (₹)     10000 non-null  int64
 15  Discount (%)            10000 non-null  int64
 16  Festival/Sale           3212 non-null   str
 17  Shipping Charge (₹)     10000 non-null  int64
 18  Delivery Speed          7751 non-null   str
 19  Delivery Time (Days)    10000 non-null  int64
 20  Subscription Status     10000 non-null  str
 21  Payment Method          10000 non-null  str
 22  Review Rating           10000 non-null  int64
 23  Return Status           10000 non-null  str
 24  Previous Purchases      10000 non-null  int64
 25  Frequency of Purchases  10000 non-null  str
dtypes: int64(8), str(18)
memory usage: 2.0 MB

In [5]:
df.describe(include='all')

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
count,10000,10000,10000,10000.000000,10000,10000,10000,7751,10000,10000,...,3212,10000.00000,7751,10000.000000,10000,10000,10000.000000,10000,10000.000000,10000
unique,10000,2581,731,NaN,2,20,2,6,3,24,...,7,NaN,3,NaN,2,7,NaN,2,NaN,5
top,TXN507808,CUST101018,2023-08-15,NaN,Male,Pune,Online,Myntra,Clothing,Dress,...,End of Season Sale,NaN,Standard,NaN,No,UPI,NaN,Not Returned,NaN,Weekly
freq,1,29,41,NaN,5449,974,7751,2078,5003,617,...,517,NaN,4945,NaN,6881,4411,NaN,8198,NaN,3487
mean,NaN,NaN,NaN,38.278100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,41.49210,NaN,3.703600,NaN,NaN,3.874900,NaN,3.211400,NaN
std,NaN,NaN,NaN,12.133041,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,64.30923,NaN,2.726223,NaN,NaN,0.912871,NaN,3.951313,NaN
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,0.000000,NaN,NaN,1.000000,NaN,0.000000,NaN
25%,NaN,NaN,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,1.000000,NaN,NaN,3.000000,NaN,0.000000,NaN
50%,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,4.000000,NaN,NaN,4.000000,NaN,2.000000,NaN
75%,NaN,NaN,NaN,49.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,79.00000,NaN,6.000000,NaN,NaN,5.000000,NaN,4.000000,NaN
max,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,199.00000,NaN,8.000000,NaN,NaN,5.000000,NaN,28.000000,NaN

In [6]:
df.isnull().sum()

Transaction ID               0
Customer ID                  0
Purchase Date                0
Age                          0
Gender                       0
Location                     0
Online/Offline               0
Online Store              2249
Category                     0
Item Purchased               0
Brand                        0
Color                        0
Size                      1035
Quantity                     0
Purchase Amount (₹)          0
Discount (%)                 0
Festival/Sale             6788
Shipping Charge (₹)          0
Delivery Speed            2249
Delivery Time (Days)         0
Subscription Status          0
Payment Method               0
Review Rating                0
Return Status                0
Previous Purchases           0
Frequency of Purchases       0
dtype: int64

In [7]:
# Put all column name in SnakeCasing i.e all lower case or upper case
df.columns = df.columns.str.lower()
df.columns =  df.columns.str.replace(' ','_')

In [8]:
df.columns

Index(['transaction_id', 'customer_id', 'purchase_date', 'age', 'gender',
       'location', 'online/offline', 'online_store', 'category',
       'item_purchased', 'brand', 'color', 'size', 'quantity',
       'purchase_amount_(₹)', 'discount_(%)', 'festival/sale',
       'shipping_charge_(₹)', 'delivery_speed', 'delivery_time_(days)',
       'subscription_status', 'payment_method', 'review_rating',
       'return_status', 'previous_purchases', 'frequency_of_purchases'],
      dtype='str')

In [9]:
df['online_store'].fillna('In-store purchase',inplace=True)
df['size'] = df.groupby('item_purchased')['size'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'N/A'))
df['festival/sale'].fillna('Standard Day',inplace=True)
df['delivery_speed'].fillna('Offline purchase',inplace=True)

0               Same Day
1       Offline purchase
2               Standard
3               Standard
4                Express
              ...
9995             Express
9996             Express
9997            Standard
9998            Standard
9999            Standard
Name: delivery_speed, Length: 10000, dtype: str

In [10]:
# create a new column age_group using feature engineering
labels = ['Young Adult', 'Adult','Middle Aged', 'Senior']
bins = [1, 18, 35, 60, 100]
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

In [11]:
df[['age','age_group']].head(10)

   age    age_group
0   51  Middle Aged
1   27        Adult
2   57  Middle Aged
3   22        Adult
4   30        Adult
5   57  Middle Aged
6   42  Middle Aged
7   47  Middle Aged
8   37  Middle Aged
9   33        Adult

In [12]:
df.isnull().sum()

transaction_id               0
customer_id                  0
purchase_date                0
age                          0
gender                       0
location                     0
online/offline               0
online_store              2249
category                     0
item_purchased               0
brand                        0
color                        0
size                         0
quantity                     0
purchase_amount_(₹)          0
discount_(%)                 0
festival/sale             6788
shipping_charge_(₹)          0
delivery_speed            2249
delivery_time_(days)         0
subscription_status          0
payment_method               0
review_rating                0
return_status                0
previous_purchases           0
frequency_of_purchases       0
age_group                    0
dtype: int64

In [13]:
# create a new column age_group using feature engineering
labels = ['Young Adult', 'Adult','Middle Aged', 'Senior']
bins = [1, 18, 35, 60, 100]
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

In [14]:
df[['age','age_group']].head(10)

   age    age_group
0   51  Middle Aged
1   27        Adult
2   57  Middle Aged
3   22        Adult
4   30        Adult
5   57  Middle Aged
6   42  Middle Aged
7   47  Middle Aged
8   37  Middle Aged
9   33        Adult

In [15]:
df['frequency_of_purchases'].unique()

<StringArray>
['Fortnightly', 'Rarely', 'Weekly', 'Monthly', 'Quarterly']
Length: 5, dtype: str

In [16]:
# Create column purchase_frequency_days
frequency_mapping={
    'Weekly': 7,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Rarely': 365

}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [17]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                      365                 Rarely
3                       14            Fortnightly
4                        7                 Weekly
5                       14            Fortnightly
6                       30                Monthly
7                       30                Monthly
8                       14            Fortnightly
9                        7                 Weekly

In [18]:
df = df.drop('online/offline', axis=1)

In [19]:
df.columns

Index(['transaction_id', 'customer_id', 'purchase_date', 'age', 'gender',
       'location', 'online_store', 'category', 'item_purchased', 'brand',
       'color', 'size', 'quantity', 'purchase_amount_(₹)', 'discount_(%)',
       'festival/sale', 'shipping_charge_(₹)', 'delivery_speed',
       'delivery_time_(days)', 'subscription_status', 'payment_method',
       'review_rating', 'return_status', 'previous_purchases',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

# **Connect to MySQL**

In [20]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.3)
Requirement already satisfied: sqlalchemy in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.16.0)

In [21]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.7.0)

In [22]:
import mysql.connector

In [23]:
from getpass import getpass

In [ ]:
password = getpass("Enter your MySQL password: ")

In [25]:
try:
    mydb = mysql.connector.connect(
        host="yourlocalhost",
        user="youruser",
        password="givepassword"
    )
except mysql.connector.Error as err:
    print("Connection Failed:", err)
else:
    print("Connection established successfully!")

Connection established successfully!

In [26]:
mycursor = mydb.cursor()

In [27]:
mycursor.execute("SHOW DATABASES")
for db in mycursor:
    print(db)

('classroom',)
('classroomtech',)
('customer_behavior',)
('dummy',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [28]:
from sqlalchemy import create_engine


engine = create_engine("mysql+pymysql://user:givepassword@host:port/database")

#Write DataFrame to MySQL
table_name = "customerk"
df.to_sql(table_name, engine, if_exists="replace", index=False)

#Read back sample
pd.read_sql("SELECT * FROM customerk LIMIT 5;", engine)

,transaction_id,customer_id,purchase_date,age,gender,location,online_store,category,item_purchased,brand,...,delivery_speed,delivery_time_(days),subscription_status,payment_method,review_rating,return_status,previous_purchases,frequency_of_purchases,age_group,purchase_frequency_days
0,TXN507808,CUST102534,2023-01-01,51,Male,Chennai,Flipkart,Clothing,Kurta,Max,...,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly,Middle Aged,14
1,TXN503830,CUST101256,2023-01-01,27,Female,Mumbai,NaN,Clothing,Shirt,Puma,...,NaN,0,No,UPI,5,Not Returned,0,Fortnightly,Adult,14
2,TXN501496,CUST100490,2023-01-01,57,Male,Hyderabad,Flipkart,Clothing,Jacket,Roadster,...,Standard,7,Yes,UPI,3,Not Returned,0,Rarely,Middle Aged,365
3,TXN501538,CUST100500,2023-01-01,22,Female,Pune,Myntra,Clothing,Kurta,Puma,...,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly,Adult,14
4,TXN504265,CUST101399,2023-01-01,30,Male,Visakhapatnam,Myntra,Accessories,Cap,Puma,...,Express,2,No,Debit Card,4,Not Returned,0,Weekly,Adult,7