**1. Importing Libraries**

In [15]:
import pandas as pd

**2. Loading Dataset**

In [16]:

df = pd.read_csv('customer_shopping_behavior.csv')

In [17]:
df.head()

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
0,TXN507808,CUST102534,2023-01-01,51,Male,Chennai,Online,Flipkart,Clothing,Kurta,...,NaN,0,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly
1,TXN503830,CUST101256,2023-01-01,27,Female,Mumbai,Offline,NaN,Clothing,Shirt,...,NaN,0,NaN,0,No,UPI,5,Not Returned,0,Fortnightly
2,TXN501496,CUST100490,2023-01-01,57,Male,Hyderabad,Online,Flipkart,Clothing,Jacket,...,NaN,0,Standard,7,Yes,UPI,3,Not Returned,0,Rarely
3,TXN501538,CUST100500,2023-01-01,22,Female,Pune,Online,Myntra,Clothing,Kurta,...,NaN,0,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly
4,TXN504265,CUST101399,2023-01-01,30,Male,Visakhapatnam,Online,Myntra,Accessories,Cap,...,NaN,99,Express,2,No,Debit Card,4,Not Returned,0,Weekly

**3. Getting Information about dataset**

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction ID          10000 non-null  str
 1   Customer ID             10000 non-null  str
 2   Purchase Date           10000 non-null  str
 3   Age                     10000 non-null  int64
 4   Gender                  10000 non-null  str
 5   Location                10000 non-null  str
 6   Online/Offline          10000 non-null  str
 7   Online Store            7751 non-null   str
 8   Category                10000 non-null  str
 9   Item Purchased          10000 non-null  str
 10  Brand                   10000 non-null  str
 11  Color                   10000 non-null  str
 12  Size                    8965 non-null   str
 13  Quantity                10000 non-null  int64
 14  Purchase Amount (₹)     10000 non-null  int64
 15  Discount (%)            10000 non-null  int64
 16  Festival/Sale           3212 non-null   str
 17  Shipping Charge (₹)     10000 non-null  int64
 18  Delivery Speed          7751 non-null   str
 19  Delivery Time (Days)    10000 non-null  int64
 20  Subscription Status     10000 non-null  str
 21  Payment Method          10000 non-null  str
 22  Review Rating           10000 non-null  int64
 23  Return Status           10000 non-null  str
 24  Previous Purchases      10000 non-null  int64
 25  Frequency of Purchases  10000 non-null  str
dtypes: int64(8), str(18)
memory usage: 2.0 MB

In [19]:
# Statistical summary of the Dataset
df.describe(include='all') # for categorical columns

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
count,10000,10000,10000,10000.000000,10000,10000,10000,7751,10000,10000,...,3212,10000.00000,7751,10000.000000,10000,10000,10000.000000,10000,10000.000000,10000
unique,10000,2581,731,NaN,2,20,2,6,3,24,...,7,NaN,3,NaN,2,7,NaN,2,NaN,5
top,TXN507808,CUST101018,2023-08-15,NaN,Male,Pune,Online,Myntra,Clothing,Dress,...,End of Season Sale,NaN,Standard,NaN,No,UPI,NaN,Not Returned,NaN,Weekly
freq,1,29,41,NaN,5449,974,7751,2078,5003,617,...,517,NaN,4945,NaN,6881,4411,NaN,8198,NaN,3487
mean,NaN,NaN,NaN,38.278100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,41.49210,NaN,3.703600,NaN,NaN,3.874900,NaN,3.211400,NaN
std,NaN,NaN,NaN,12.133041,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,64.30923,NaN,2.726223,NaN,NaN,0.912871,NaN,3.951313,NaN
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,0.000000,NaN,NaN,1.000000,NaN,0.000000,NaN
25%,NaN,NaN,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,1.000000,NaN,NaN,3.000000,NaN,0.000000,NaN
50%,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,4.000000,NaN,NaN,4.000000,NaN,2.000000,NaN
75%,NaN,NaN,NaN,49.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,79.00000,NaN,6.000000,NaN,NaN,5.000000,NaN,4.000000,NaN
max,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,199.00000,NaN,8.000000,NaN,NaN,5.000000,NaN,28.000000,NaN

In [38]:
df.describe() # for numerical columns

,age,quantity,purchase_amount_(₹),discount_(%),shipping_charge_(₹),delivery_time_(days),review_rating,previous_purchases,purchase_frequency_days
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000
mean,38.278100,1.425100,1889.882000,32.916300,41.49210,3.703600,3.874900,3.211400,31.052500
std,12.133041,0.761346,2102.301836,21.440617,64.30923,2.726223,0.912871,3.951313,63.243465
min,18.000000,1.000000,67.000000,0.000000,0.00000,0.000000,1.000000,0.000000,7.000000
25%,28.000000,1.000000,600.000000,12.000000,0.00000,1.000000,3.000000,0.000000,7.000000
50%,38.000000,1.000000,1207.000000,33.000000,0.00000,4.000000,4.000000,2.000000,14.000000
75%,49.000000,2.000000,2376.000000,52.000000,79.00000,6.000000,5.000000,4.000000,30.000000
max,59.000000,4.000000,22306.000000,70.000000,199.00000,8.000000,5.000000,28.000000,365.000000

In [20]:
df.isnull().sum()

Transaction ID               0
Customer ID                  0
Purchase Date                0
Age                          0
Gender                       0
Location                     0
Online/Offline               0
Online Store              2249
Category                     0
Item Purchased               0
Brand                        0
Color                        0
Size                      1035
Quantity                     0
Purchase Amount (₹)          0
Discount (%)                 0
Festival/Sale             6788
Shipping Charge (₹)          0
Delivery Speed            2249
Delivery Time (Days)         0
Subscription Status          0
Payment Method               0
Review Rating                0
Return Status                0
Previous Purchases           0
Frequency of Purchases       0
dtype: int64

In [21]:
# Put all column name in SnakeCasing i.e all lower case or upper case
df.columns = df.columns.str.lower()
df.columns =  df.columns.str.replace(' ','_')

In [22]:
df.columns

Index(['transaction_id', 'customer_id', 'purchase_date', 'age', 'gender',
       'location', 'online/offline', 'online_store', 'category',
       'item_purchased', 'brand', 'color', 'size', 'quantity',
       'purchase_amount_(₹)', 'discount_(%)', 'festival/sale',
       'shipping_charge_(₹)', 'delivery_speed', 'delivery_time_(days)',
       'subscription_status', 'payment_method', 'review_rating',
       'return_status', 'previous_purchases', 'frequency_of_purchases'],
      dtype='str')

**4. Data Cleaning**

In [23]:
# Drop unnecessary column from the dataset
df = df.drop('online/offline', axis=1)

In [36]:
# Filling the missing values in the dataset
df['online_store'] = df['online_store'].fillna('In-store purchase')
df['size'] = df.groupby('item_purchased')['size'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'N/A'))
df['festival/sale'] = df['festival/sale'].fillna('Standard Day')
df['delivery_speed'] = df['delivery_speed'].fillna('Offline purchase')

In [25]:
# create a new column age_group using feature engineering
labels = ['Young Adult', 'Adult','Middle Aged', 'Senior']
bins = [1, 18, 35, 60, 100]
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

In [26]:
df[['age','age_group']].head(10)

   age    age_group
0   51  Middle Aged
1   27        Adult
2   57  Middle Aged
3   22        Adult
4   30        Adult
5   57  Middle Aged
6   42  Middle Aged
7   47  Middle Aged
8   37  Middle Aged
9   33        Adult

In [37]:
df.isnull().sum()

transaction_id             0
customer_id                0
purchase_date              0
age                        0
gender                     0
location                   0
online_store               0
category                   0
item_purchased             0
brand                      0
color                      0
size                       0
quantity                   0
purchase_amount_(₹)        0
discount_(%)               0
festival/sale              0
shipping_charge_(₹)        0
delivery_speed             0
delivery_time_(days)       0
subscription_status        0
payment_method             0
review_rating              0
return_status              0
previous_purchases         0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

**5. Feature Engineering**

In [28]:
# create a new column age_group using feature engineering
labels = ['Young Adult', 'Adult','Middle Aged', 'Senior']
bins = [1, 18, 35, 60, 100]
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

In [29]:
df[['age','age_group']].head(10)

   age    age_group
0   51  Middle Aged
1   27        Adult
2   57  Middle Aged
3   22        Adult
4   30        Adult
5   57  Middle Aged
6   42  Middle Aged
7   47  Middle Aged
8   37  Middle Aged
9   33        Adult

In [30]:
df['frequency_of_purchases'].unique()

<StringArray>
['Fortnightly', 'Rarely', 'Weekly', 'Monthly', 'Quarterly']
Length: 5, dtype: str

In [31]:
# Create column purchase_frequency_days
frequency_mapping={
    'Weekly': 7,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Rarely': 365

}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [32]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                      365                 Rarely
3                       14            Fortnightly
4                        7                 Weekly
5                       14            Fortnightly
6                       30                Monthly
7                       30                Monthly
8                       14            Fortnightly
9                        7                 Weekly

In [33]:
df.columns

Index(['transaction_id', 'customer_id', 'purchase_date', 'age', 'gender',
       'location', 'online_store', 'category', 'item_purchased', 'brand',
       'color', 'size', 'quantity', 'purchase_amount_(₹)', 'discount_(%)',
       'festival/sale', 'shipping_charge_(₹)', 'delivery_speed',
       'delivery_time_(days)', 'subscription_status', 'payment_method',
       'review_rating', 'return_status', 'previous_purchases',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [ ]:
# Save the cleaned dataset to a new CSV file
df.to_csv('cleaned_customer_shopping_behavior.csv', index = False)

# **Connect to MySQL**

In [35]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Using cached pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.1.2-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Using cached pymysql-1.2.3-py3-none-any.whl (46 kB)
Downloading sqlalchemy-2.1.2-cp314-cp314-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 2.2 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.4 MB 2.5 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.4 MB 2.5 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.4 MB 2.5 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.4 MB 2.5 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.4 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 1.8/2.4 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.4 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 1.3 MB/s  0:00:01
Installing collected packages: sqlalchemy, pymysql

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [pymysql]
   ---------------------------------------- 2/2 [pymysql]

Successfully installed pymysql-1.2.3 sqlalchemy-2.1.2

In [39]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Using cached mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Using cached mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl (18.2 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

In [40]:
import mysql.connector

In [41]:
from getpass import getpass

In [42]:
password = getpass("Enter your MySQL password: ")

In [ ]:
try:
    mydb = mysql.connector.connect(
        host="yourhost",
        user="username",
        password="password"
    )
except mysql.connector.Error as err:
    print("Connection Failed:", err)
else:
    print("Connection established successfully!")

Connection established successfully!

In [44]:
mycursor = mydb.cursor()

In [45]:
mycursor.execute("SHOW DATABASES")
for db in mycursor:
    print(db)

('classroom',)
('classroomtech',)
('dummy',)
('information_schema',)
('join_demo',)
('mysql',)
('performance_schema',)
('sys',)

In [ ]:
from sqlalchemy import create_engine


engine = create_engine("mysql+pymysql://username:password@yourhost:port/database")

#Write DataFrame to MySQL
table_name = "customerk"
# Create the database if it does not already exist
db_name = "customer_shopping"
mycursor.execute(f"CREATE DATABASE IF NOT EXISTS {db_name}")

# Reconnect to the actual database
engine = create_engine(f"mysql+pymysql://username:password@yourhost:port/{db_name}")

# Write DataFrame to MySQL
df.to_sql(table_name, con=engine, if_exists="replace", index=False)

#Read back sample
pd.read_sql("SELECT * FROM customerk LIMIT 20;", engine)

,transaction_id,customer_id,purchase_date,age,gender,location,online_store,category,item_purchased,brand,...,delivery_speed,delivery_time_(days),subscription_status,payment_method,review_rating,return_status,previous_purchases,frequency_of_purchases,age_group,purchase_frequency_days
0,TXN507808,CUST102534,2023-01-01,51,Male,Chennai,Flipkart,Clothing,Kurta,Max,...,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly,Middle Aged,14
1,TXN503830,CUST101256,2023-01-01,27,Female,Mumbai,In-store purchase,Clothing,Shirt,Puma,...,Offline purchase,0,No,UPI,5,Not Returned,0,Fortnightly,Adult,14
2,TXN501496,CUST100490,2023-01-01,57,Male,Hyderabad,Flipkart,Clothing,Jacket,Roadster,...,Standard,7,Yes,UPI,3,Not Returned,0,Rarely,Middle Aged,365
3,TXN501538,CUST100500,2023-01-01,22,Female,Pune,Myntra,Clothing,Kurta,Puma,...,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly,Adult,14
4,TXN504265,CUST101399,2023-01-01,30,Male,Visakhapatnam,Myntra,Accessories,Cap,Puma,...,Express,2,No,Debit Card,4,Not Returned,0,Weekly,Adult,7
5,TXN509250,CUST102952,2023-01-01,57,Male,Kochi,In-store purchase,Accessories,Watch,Roadster,...,Offline purchase,0,No,Credit Card,5,Not Returned,0,Fortnightly,Middle Aged,14
6,TXN501814,CUST100596,2023-01-01,42,Male,Hyderabad,Myntra,Footwear,Formal Shoes,Nike,...,Standard,4,No,UPI,3,Not Returned,0,Monthly,Middle Aged,30
7,TXN500031,CUST100007,2023-01-01,47,Male,Pune,Myntra,Clothing,Jacket,H&M,...,Standard,5,No,Credit Card,5,Not Returned,0,Monthly,Middle Aged,30
8,TXN501550,CUST100505,2023-01-01,37,Female,Ahmedabad,In-store purchase,Clothing,Saree,H&M,...,Offline purchase,0,Yes,UPI,5,Returned,0,Fortnightly,Middle Aged,14
9,TXN505122,CUST101684,2023-01-01,33,Male,Visakhapatnam,Amazon,Clothing,Hoodie,HRX,...,Standard,4,Yes,Cash on Delivery,5,Returned,0,Weekly,Adult,7
10,TXN501568,CUST100510,2023-01-01,59,Male,Chennai,Ajio,Clothing,Jacket,HRX,...,Standard,8,Yes,UPI,3,Not Returned,0,Weekly,Middle Aged,7
11,TXN508080,CUST102612,2023-01-01,25,Male,Mumbai,Flipkart,Footwear,Boots,Max,...,Express,4,No,Cash on Delivery,3,Not Returned,0,Fortnightly,Adult,14
12,TXN501212,CUST100365,2023-01-01,39,Male,Chandigarh,Amazon,Footwear,Sandals,Zara,...,Standard,8,No,Credit Card,3,Not Returned,0,Fortnightly,Middle Aged,14
13,TXN500349,CUST100086,2023-01-02,22,Male,Mumbai,Shein,Clothing,T-shirt,Puma,...,Standard,4,No,UPI,5,Returned,0,Weekly,Adult,7
14,TXN504688,CUST101565,2023-01-02,37,Female,Hyderabad,Myntra,Clothing,Kurta,Levis,...,Standard,8,No,Credit Card,3,Not Returned,0,Quarterly,Middle Aged,90
15,TXN503278,CUST101052,2023-01-02,39,Female,Delhi,Myntra,Clothing,Kurta,Allen Solly,...,Standard,5,No,Debit Card,5,Not Returned,0,Fortnightly,Middle Aged,14
16,TXN507411,CUST102428,2023-01-02,49,Male,Bangalore,Meesho,Footwear,Boots,HRX,...,Standard,6,No,Credit Card,3,Not Returned,0,Weekly,Middle Aged,7
17,TXN502224,CUST100729,2023-01-02,45,Male,Indore,Flipkart,Clothing,Trousers,Max,...,Express,4,No,Credit Card,4,Not Returned,0,Monthly,Middle Aged,30
18,TXN505960,CUST101941,2023-01-02,28,Female,Chennai,Myntra,Footwear,Slippers,Zara,...,Standard,6,Yes,UPI,4,Not Returned,0,Weekly,Adult,7
19,TXN507732,CUST102512,2023-01-03,58,Female,Chennai,In-store purchase,Clothing,Jacket,Max,...,Offline purchase,0,Yes,UPI,5,Returned,0,Fortnightly,Middle Aged,14