<a href="https://colab.research.google.com/github/rudrascience/Customer-Shopping-Trends-Analysis/blob/main/Kaggle_Customer_Shopping_Behavior.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/customer_shopping_behavior.csv')

In [ ]:
df.head()

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
0,TXN507808,CUST102534,2023-01-01,51,Male,Chennai,Online,Flipkart,Clothing,Kurta,...,NaN,0,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly
1,TXN503830,CUST101256,2023-01-01,27,Female,Mumbai,Offline,NaN,Clothing,Shirt,...,NaN,0,NaN,0,No,UPI,5,Not Returned,0,Fortnightly
2,TXN501496,CUST100490,2023-01-01,57,Male,Hyderabad,Online,Flipkart,Clothing,Jacket,...,NaN,0,Standard,7,Yes,UPI,3,Not Returned,0,Rarely
3,TXN501538,CUST100500,2023-01-01,22,Female,Pune,Online,Myntra,Clothing,Kurta,...,NaN,0,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly
4,TXN504265,CUST101399,2023-01-01,30,Male,Visakhapatnam,Online,Myntra,Accessories,Cap,...,NaN,99,Express,2,No,Debit Card,4,Not Returned,0,Weekly

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction ID          10000 non-null  object
 1   Customer ID             10000 non-null  object
 2   Purchase Date           10000 non-null  object
 3   Age                     10000 non-null  int64
 4   Gender                  10000 non-null  object
 5   Location                10000 non-null  object
 6   Online/Offline          10000 non-null  object
 7   Online Store            7751 non-null   object
 8   Category                10000 non-null  object
 9   Item Purchased          10000 non-null  object
 10  Brand                   10000 non-null  object
 11  Color                   10000 non-null  object
 12  Size                    8965 non-null   object
 13  Quantity                10000 non-null  int64
 14  Purchase Amount (₹)     10000 non-null  int64
 15  Discount (%)            10000 non-null  int64
 16  Festival/Sale           3212 non-null   object
 17  Shipping Charge (₹)     10000 non-null  int64
 18  Delivery Speed          7751 non-null   object
 19  Delivery Time (Days)    10000 non-null  int64
 20  Subscription Status     10000 non-null  object
 21  Payment Method          10000 non-null  object
 22  Review Rating           10000 non-null  int64
 23  Return Status           10000 non-null  object
 24  Previous Purchases      10000 non-null  int64
 25  Frequency of Purchases  10000 non-null  object
dtypes: int64(8), object(18)
memory usage: 2.0+ MB

In [ ]:
df.describe(include='all')

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
count,10000,10000,10000,10000.000000,10000,10000,10000,7751,10000,10000,...,3212,10000.00000,7751,10000.000000,10000,10000,10000.000000,10000,10000.000000,10000
unique,10000,2581,731,NaN,2,20,2,6,3,24,...,7,NaN,3,NaN,2,7,NaN,2,NaN,5
top,TXN502886,CUST101018,2023-08-15,NaN,Male,Pune,Online,Myntra,Clothing,Dress,...,End of Season Sale,NaN,Standard,NaN,No,UPI,NaN,Not Returned,NaN,Weekly
freq,1,29,41,NaN,5449,974,7751,2078,5003,617,...,517,NaN,4945,NaN,6881,4411,NaN,8198,NaN,3487
mean,NaN,NaN,NaN,38.278100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,41.49210,NaN,3.703600,NaN,NaN,3.874900,NaN,3.211400,NaN
std,NaN,NaN,NaN,12.133041,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,64.30923,NaN,2.726223,NaN,NaN,0.912871,NaN,3.951313,NaN
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,0.000000,NaN,NaN,1.000000,NaN,0.000000,NaN
25%,NaN,NaN,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,1.000000,NaN,NaN,3.000000,NaN,0.000000,NaN
50%,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00000,NaN,4.000000,NaN,NaN,4.000000,NaN,2.000000,NaN
75%,NaN,NaN,NaN,49.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,79.00000,NaN,6.000000,NaN,NaN,5.000000,NaN,4.000000,NaN
max,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,199.00000,NaN,8.000000,NaN,NaN,5.000000,NaN,28.000000,NaN

In [ ]:
df.isnull().sum()

Transaction ID               0
Customer ID                  0
Purchase Date                0
Age                          0
Gender                       0
Location                     0
Online/Offline               0
Online Store              2249
Category                     0
Item Purchased               0
Brand                        0
Color                        0
Size                      1035
Quantity                     0
Purchase Amount (₹)          0
Discount (%)                 0
Festival/Sale             6788
Shipping Charge (₹)          0
Delivery Speed            2249
Delivery Time (Days)         0
Subscription Status          0
Payment Method               0
Review Rating                0
Return Status                0
Previous Purchases           0
Frequency of Purchases       0
dtype: int64

In [41]:
df['Online Store'].fillna('In-store purchase', inplace=True)
df['Size'] = df.groupby('Item Purchased')['Size'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'N/A'))
df['Festival/Sale'].fillna('Standard Day', inplace=True)
df['Delivery Speed'].fillna('N/A(Offline purchase)', inplace=True)

/tmp/ipykernel_1603/306819165.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Online Store'].fillna('In-store purchase', inplace=True)
/tmp/ipykernel_1603/306819165.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Festival/Sale'].fillna('Standard Day', inplace=True)
/tmp/ipykernel_1603/306819165.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery Speed'].fillna('N/A(Offline purchase)', inplace=True)

In [42]:
df.isnull().sum()

Transaction ID            0
Customer ID               0
Purchase Date             0
Age                       0
Gender                    0
Location                  0
Online/Offline            0
Online Store              0
Category                  0
Item Purchased            0
Brand                     0
Color                     0
Size                      0
Quantity                  0
Purchase Amount (₹)       0
Discount (%)              0
Festival/Sale             0
Shipping Charge (₹)       0
Delivery Speed            0
Delivery Time (Days)      0
Subscription Status       0
Payment Method            0
Review Rating             0
Return Status             0
Previous Purchases        0
Frequency of Purchases    0
dtype: int64

In [71]:
# Put all column name in SnakeCasing i.e all lower case or upper case
df.columns = df.columns.str.lower()
df.columns =  df.columns.str.replace(' ','_')

In [72]:
df.columns

Index(['transaction_id', 'customer_id', 'purchase_date', 'age', 'gender',
       'location', 'online/offline', 'online_store', 'category',
       'item_purchased', 'brand', 'color', 'size', 'quantity',
       'purchase_amount_(₹)', 'discount_(%)', 'festival/sale',
       'shipping_charge_(₹)', 'delivery_speed', 'delivery_time_(days)',
       'subscription_status', 'payment_method', 'review_rating',
       'return_status', 'previous_purchases', 'frequency_of_purchases'],
      dtype='object')

In [73]:
# create a new column age_group using feature engineering
labels = ['Young Adult', 'Adult', 'Senior']
bins = [18, 30, 60, 100]
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)